spring:
  application:
    name: apf_trading_v2

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://10.0.0.101:5432/apf_app_cms_db?currentSchema=trading}
    username: ${SPRING_DATASOURCE_USERNAME:apf_app_cms_user}
    password: ${SPRING_DATASOURCE_PASSWORD:12345aA@}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
    hikari:
      schema: ${SPRING_DATASOURCE_HIKARI_SCHEMA:trading}

  rabbitmq:
    host: 10.0.0.72
    port: 5672
    username: abond
    password: abond
    queue:
      name: TX_HNX_SEND_ORDER
    exchange:
      order: TX_HNX_PUSH_MESSAGE
      message: TX_HNX_SEND_MESSAGE

  redis:
    host: 10.0.0.187
    port: 6379
    username: shm_digital
    password: Apec*@2024

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://sso.apecgroup.net/realms/APECFinance
          jwk-set-uri: https://sso.apecgroup.net/realms/APECFinance/protocol/openid-connect/certs

    keycloak:
      realm: APECFinance
      auth-server-url: https://sso.apecgroup.net/realms/APECFinance
      resource: apec-finance-api
      credentials:
        secret: UEM6v6kLpmDee1oTQgcclgsVR1jiXmdL
      use-resource-role-mappings: true
server:
  port: 8082
  servlet:
    context-path: /v2/api/apec-finance/trading
